(function(root){
'use strict';
const E=root.HODOKU,$=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)];
const storeKey='hodoku-v1';
let saved={model:3,plans:[[],[],[]],best:{},last:0};
try{const v=JSON.parse(localStorage.getItem(storeKey)||'null');if(v&&typeof v==='object'){saved.best=v.model===3&&v.best&&typeof v.best==='object'?v.best:{};saved.last=Number.isInteger(v.last)&&v.last>=0&&v.last<3?v.last:0;if(Array.isArray(v.plans))saved.plans=E.STAGES.map((s,i)=>E.validatePlan(s,v.plans[i]).ok?v.plans[i]:[]);}}catch(_){}
const state={stage:0,plan:saved.plans[0]||[],selected:1,tab:'timing',mode:'intro',before:false,heat:false,paused:false,speed:20,hover:-1,ghost:-1,sound:false,result:null};
const atlas=new root.HODOKU_ATLAS($('map'));
let beforeSim,afterSim,acc=0,last=0,lastUI=0,toastTimer,computing=false,previousFocus=null;
const stage=()=>E.STAGES[state.stage];
const config=()=>E.configFromPlan(stage(),state.plan);
const shownSim=()=>state.before?beforeSim:afterSim;
const money=n=>String(n);
const fmt=(n,d=0)=>Number(n).toLocaleString('ja-JP',{minimumFractionDigits:d,maximumFractionDigits:d});
const signed=(n,d=0)=>(n>0?'+':n<0?'−':'±')+fmt(Math.abs(n),d);
const iconArrow='<span aria-hidden="true">↗</span>';
function persist(){saved.plans[state.stage]=JSON.parse(JSON.stringify(state.plan));saved.last=state.stage;try{localStorage.setItem(storeKey,JSON.stringify(saved));}catch(_){}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3300);}
function resetSim(preview=true){const d=E.schedule(stage());beforeSim=new E.Simulation(stage(),E.baseConfig(stage()),d);afterSim=new E.Simulation(stage(),config(),d);if(preview){beforeSim.advance(250);afterSim.advance(250);}acc=0;last=0;}
function planKey(p){return p.type==='sync'?'sync':p.type+':'+p.node;}
function remove(index){if(state.mode==='running')return;state.plan.splice(index,1);state.result=null;persist();resetSim();updateAll();audio.tap(0);}
function proposed(type,node,value){const next=state.plan.map(p=>({...p})),key=type==='sync'?'sync':type+':'+node;const i=next.findIndex(p=>planKey(p)===key);const p={type,node,value};
 if(i>=0)next.splice(i,1);
 const defaults=E.configFromPlan(stage(),next);const same=type==='split'?value===defaults.junctions[node].green:type==='offset'?value===defaults.junctions[node].offset:false;
 if(!same){if(i>=0)next.splice(i,0,p);else next.push(p);}
 return next;
}
function apply(type,node,value){if(state.mode==='running')return;const next=proposed(type,node,value),v=E.validatePlan(stage(),next);if(!v.ok){toast(v.reason);audio.tap(-1);return;}
 if(JSON.stringify(next)===JSON.stringify(state.plan)){toast('その変更は、すでに書き込まれています。');return;}
 state.plan=next;state.result=null;state.before=false;persist();resetSim();updateAll();audio.tap(1);toast(next.length?`${E.TOOLS[type].name}を書き込みました。残り ${3-next.length} 手。`:'もとの設定に戻しました。');}
function canApply(type,node,value){return state.mode!=='running'&&E.validatePlan(stage(),proposed(type,node,value)).ok;}
function toggleBuild(type){const i=state.plan.findIndex(p=>p.type===type&&p.node===state.selected);if(i>=0)remove(i);else apply(type,state.selected,true);}
function selectNode(j,scroll=false){state.selected=j;atlas.select?.(j);state.ghost=-1;updatePanel();updateNodeTabs();audio.tap(0);if(scroll&&innerWidth<761)$('workbench').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
function updateNodeTabs(){ $('node-tabs').innerHTML=E.POINTS.slice(1,6).map((n,i)=>`<button class="${i===state.selected?'active':''}" aria-pressed="${i===state.selected}" title="${n.name}" aria-label="${i+1} ${n.name}">${String(i+1).padStart(2,'0')}</button>`).join('');[...$('node-tabs').children].forEach((b,i)=>b.addEventListener('click',()=>selectNode(i)));}
function updateResources(){const v=E.validatePlan(stage(),state.plan);$('moves').innerHTML=Array.from({length:3},(_,i)=>`<span class="move-box ${i<state.plan.length?'used':''}" aria-label="${i<state.plan.length?'使用済み':'未使用'}">${i+1}</span>`).join('');$('budget').textContent=money(stage().budget-v.cost);$('budget-total').textContent='/ '+stage().budget;$('budget-fill').style.width=((stage().budget-v.cost)/stage().budget*100)+'%';
 $('goal').innerHTML=`<strong>街全体の待ち時間を ${stage().target}% 以上減らす。</strong><br>歩行者の平均待ち ＋6秒以内 ／ 脇道 ＋15秒以内。`;
 $('run').innerHTML=state.mode==='running'?'同じ朝で、比べています <span>···</span>':'この案で、朝を流す <span>→</span>';$('run').disabled=state.mode==='running'||computing;$('mobile-run').classList.toggle('hidden',state.mode==='running');
 $('clear-plan').disabled=state.mode==='running'||!state.plan.length;
}
function updatePanel(){const j=state.selected,n=E.POINTS[j+1],c=config().junctions[j];$('node-id').textContent='JUNCTION '+String(j+1).padStart(2,'0');$('node-name').textContent=n.name;$$('[data-tool-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.toolTab===state.tab);b.setAttribute('aria-selected',String(b.dataset.toolTab===state.tab));});const blocked=state.mode==='running'?'disabled':'';
 if(state.tab==='timing'){
  $('tool-panel').innerHTML=`<section class="tool-block"><div class="tool-head"><strong>青の配分を変える</strong><span class="cost">4 pt</span></div><p class="tool-desc">主道に時間を渡すと、脇道と歩行者の時間が減る。切替の黄信号と安全確認は必ず残します。</p><label for="green-range" class="slider-labels"><span>主道枠 <strong id="green-value">${c.green}</strong> 秒</span><span>脇道 <strong id="cross-value">${82-c.green}</strong> 秒</span></label><input id="green-range" type="range" min="24" max="64" step="2" value="${c.green}" ${blocked} aria-label="主道の青信号の秒数"><button id="apply-split" class="secondary" ${blocked}>この配分を書き込む ${iconArrow}</button></section>
  <section class="tool-block"><div class="tool-head"><strong>右折だけの青をつくる</strong><span class="cost">12 pt</span></div><p class="tool-desc">主道枠の12秒を、切替4秒＋右折矢印8秒に。対向直進と横断を止めて右折を流します。主道の直進時間は短くなります。</p><button id="build-right-arrow" class="secondary ${c.rightArrow?'active':''}" ${((j===0||j===4)||(!c.rightArrow&&!canApply('rightArrow',j,true))||blocked)?'disabled':''} aria-pressed="${c.rightArrow}">${c.rightArrow?'右折専用信号を取り消す':j===0||j===4?'ここには右折需要がありません':'右折専用信号をつける'} <span aria-hidden="true">→</span></button></section>
  <section class="tool-block"><div class="tool-head"><strong>青になる拍をずらす</strong><span class="cost">3 pt</span></div><p class="tool-desc">車の列が着くころに、青へ。青の長さは変わりません。</p><label for="offset-range" class="slider-labels"><span>青の開始</span><span><strong id="offset-value">${c.offset}</strong> / 90 秒</span></label><input id="offset-range" type="range" min="0" max="89" step="1" value="${c.offset}" ${blocked} aria-label="青信号の開始時刻"><button id="apply-offset" class="secondary" ${blocked}>この拍を書き込む ${iconArrow}</button></section>
  <section class="tool-block"><div class="tool-head"><strong>青を、一筆でつなぐ</strong><span class="cost">14 pt</span></div><p class="tool-desc">5つの信号を走行時間で連動。逆向きの流れには、不利になることも。</p><div class="sync-options"><button id="sync-north" class="${config().sync===1?'active':''}" ${!canApply('sync',-1,1)?'disabled':''}>南 → 北へ</button><button id="sync-south" class="${config().sync===-1?'active':''}" ${!canApply('sync',-1,-1)?'disabled':''}>北 → 南へ</button></div></section>`;
  $('build-right-arrow').addEventListener('click',()=>toggleBuild('rightArrow'));
  const gr=$('green-range'),or=$('offset-range');
  function greenUI(){$('green-value').textContent=gr.value;$('cross-value').textContent=82-Number(gr.value);$('apply-split').disabled=!canApply('split',j,Number(gr.value));}
  function offsetUI(){$('offset-value').textContent=or.value;$('apply-offset').disabled=!canApply('offset',j,Number(or.value));}
  gr.addEventListener('input',greenUI);or.addEventListener('input',offsetUI);greenUI();offsetUI();
  $('apply-split').addEventListener('click',()=>apply('split',j,Number(gr.value)));$('apply-offset').addEventListener('click',()=>apply('offset',j,Number(or.value)));$('sync-north').addEventListener('click',()=>apply('sync',-1,1));$('sync-south').addEventListener('click',()=>apply('sync',-1,-1));
 }else{
  const noTurns=j===0||j===4,existingPocket=(stage().existingPockets||[]).includes(j);
  $('tool-panel').innerHTML=`<section class="tool-block"><div class="structure"><svg viewBox="0 0 46 62" aria-hidden="true"><path d="M11 58V7M30 58V29Q30 22 39 22M30 7V15M20 58V39Q20 30 29 30"/><path d="M16 13L11 7 6 13M34 17L40 22 34 27"/></svg><div><div class="tool-head"><strong>右折レーンを縫い足す</strong><span class="cost">20 pt</span></div><p class="tool-desc">曲がる車と、まっすぐ進む車を分ける。曲がり待ちの後ろにいた列が動き出す。</p></div></div><button id="build-pocket" class="secondary ${c.pocket?'active':''}" ${(noTurns||existingPocket||(!c.pocket&&!canApply('pocket',j,true))||blocked)?'disabled':''}>${existingPocket?'既設の右折レーンです':c.pocket?'このレーンを取り消す':noTurns?'ここには右折需要がありません':'ここにレーンを足す'} ${iconArrow}</button></section>
  <section class="tool-block"><div class="structure"><svg viewBox="0 0 46 62" aria-hidden="true"><path d="M3 39H43M3 44H43M10 60C10 35 12 15 35 3M16 60C16 36 18 20 40 8"/><path d="M17 30V44M27 17V29" stroke-dasharray="2 3"/></svg><div><div class="tool-head"><strong>ひとつ、上を通す</strong><span class="cost">70 pt</span></div><p class="tool-desc">直進する車だけを信号から解放。出口の先が詰まっていたら、高架も止まる。</p></div></div><button id="build-flyover" class="secondary ${c.flyover?'active':''}" ${(!c.flyover&&!canApply('flyover',j,true))||blocked?'disabled':''}>${c.flyover?'この高架を取り消す':stage().budget<70?'この景では予算が足りません':'ここに高架を架ける'} ${iconArrow}</button></section>
  <p class="tool-desc" style="margin-top:19px">橋は、解決のひとつ。<br>でも、ときには数秒の変更が勝つ。</p>`;
  $('build-pocket').addEventListener('click',()=>toggleBuild('pocket'));$('build-flyover').addEventListener('click',()=>toggleBuild('flyover'));
  $('build-flyover').addEventListener('mouseenter',()=>{if(!$('build-flyover').disabled)state.ghost=j;});$('build-flyover').addEventListener('mouseleave',()=>state.ghost=-1);
 }
}
function planDescription(p){const name=p.type==='sync'?'全線':String(p.node+1).padStart(2,'0');let detail=E.TOOLS[p.type].name;if(p.type==='split')detail+=' '+p.value+'秒';if(p.type==='offset')detail+=' '+p.value+'秒';if(p.type==='sync')detail+=' '+(p.value===1?'南→北':'北→南');return name+' / '+detail;}
function updatePlan(){const list=$('plan-list');if(!state.plan.length){list.innerHTML='<div class="empty-plan">まだ、何も変えていません。<br>まずは番号 02 の流れを観察してみよう。</div>';return;}list.innerHTML=state.plan.map((p,i)=>`<div class="plan-item"><span class="index">${i+1}</span><span class="plan-name">${planDescription(p)}</span><span class="plan-cost">${E.TOOLS[p.type].cost}</span><button aria-label="${planDescription(p)}を取り消す" ${state.mode==='running'?'disabled':''}>×</button></div>`).join('');[...list.querySelectorAll('button')].forEach((b,i)=>b.addEventListener('click',()=>remove(i)));}
function updateScenes(){$('scenes').innerHTML='<span class="scene-caption">SCENES</span>'+E.STAGES.map((s,i)=>{const best=saved.best[i],stars=best&&Number.isFinite(best.stars)?Math.max(0,Math.min(3,best.stars)):0;return `<button class="${state.stage===i?'active':''}" aria-pressed="${state.stage===i}" aria-label="第${i+1}景 ${s.name}" title="${s.name}">${s.no}<span class="scene-stars">${'●'.repeat(stars)}</span></button>`;}).join('');[...$('scenes').querySelectorAll('button')].forEach((b,i)=>b.addEventListener('click',()=>changeStage(i)));}
function updateAll(){const s=stage();$('stage-no').textContent='SCENE '+s.no;$('stage-name').textContent=s.name;$('stage-story').textContent=s.story;$('map-note').innerHTML='<span class="note-cross">＋</span>'+(state.mode==='running'?'計測中。原案と同じ車、同じ出発時刻で比較。':'交差点の番号に触れて、ほどき方を選ぶ。');$('before').setAttribute('aria-pressed',String(state.before));$('before').innerHTML=state.before?'あなたの案へ <span>↔</span>':'原案を見る <span>↔</span>';$('heat').setAttribute('aria-pressed',String(state.heat));$('time-start').textContent=String(s.hour).padStart(2,'0')+':00';$('time-end').textContent=String(s.hour).padStart(2,'0')+':20';$('skip').classList.toggle('hidden',state.mode!=='running');$('pause').textContent=state.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',state.paused?'再生':'一時停止');$('speed').textContent='×'+state.speed;updateResources();updateNodeTabs();updatePanel();updatePlan();updateScenes();updateLive();}
function startGame(){state.mode='planning';state.paused=false;$('shell').classList.remove('is-intro');$('transport').classList.remove('hidden');resetSim();updateAll();requestAnimationFrame(()=>atlas.resize());audio.tap(1);}
function cover(){if($('modal').open)$('modal').close();state.mode='intro';state.paused=false;state.before=false;$('shell').classList.add('is-intro');$('transport').classList.add('hidden');resetSim();requestAnimationFrame(()=>atlas.resize());}
function changeStage(i){if(computing)return;persist();state.stage=i;state.plan=JSON.parse(JSON.stringify(saved.plans[i]||[]));state.selected=i===1?2:1;state.mode='planning';state.before=false;state.result=null;state.paused=false;state.ghost=-1;resetSim();updateAll();persist();audio.tap(1);}
function run(){if(state.mode==='running'||computing)return;state.mode='running';state.paused=false;state.before=false;state.result=null;resetSim(false);updateAll();toast('あなたの案と原案に、同じ朝を流します。');if(innerWidth<761)$('shell').scrollIntoView({behavior:'smooth'});audio.tap(2);}
function completeRun(){if(state.mode!=='running')return;state.result=E.judge(stage(),state.plan,beforeSim.metrics(),afterSim.metrics());state.mode='result';state.paused=true;const r=state.result;const best=saved.best[state.stage];if(!best||r.score>best.score)saved.best[state.stage]={score:r.score,stars:r.stars,improvement:r.improvement,plan:JSON.parse(JSON.stringify(state.plan))};else if(r.stars>best.stars)best.stars=r.stars;persist();updateAll();showResults();audio.chord(r.win);}
function skip(){if(state.mode!=='running'||computing)return;computing=true;$('skip').disabled=true;$('skip').textContent='計測…';setTimeout(()=>{beforeSim.finish();afterSim.finish();computing=false;$('skip').disabled=false;$('skip').textContent='結果まで →';completeRun();},25);}
function retry(){closeModal();state.mode='planning';state.paused=false;state.before=false;resetSim();updateAll();}
function updateLive(){if(!afterSim)return;const sim=shownSim(),sg=sim.signalAt(state.selected),q=sim.queueCounts();const secs=sg.main?sg.mainEnd-sg.phase:sg.arrow?sg.green-sg.phase:sg.cross?86-sg.phase:0;$('signal-seconds').textContent=secs>0?Math.ceil(secs):'·';$('signal-dial').style.background=`conic-gradient(${sg.main||sg.arrow?'var(--green)':sg.cross||sg.mainAmber||sg.crossAmber?'var(--yellow)':'var(--red)'} ${sg.phase/90*360}deg,#d9d9ca 0)`;$('node-status').textContent=sg.held?'交差点内の車が抜けるのを待っています':sg.arrow?'→ 右折専用 / 対向直進・横断は赤':sg.main?'主道が青'+(sg.turn?' / 右折の間合い':''):sg.cross?(sg.walk?'脇道が青 / 横断できる':'脇道が青 / 横断の終了待ち'):sg.mainAmber||sg.crossAmber?'黄信号 / 新たな進入は停止':'すべて赤 / 安全に切替';$('node-queue').textContent='待ち '+q[state.selected]*E.SAMPLE+' 台';const seconds=Math.min(E.DURATION,sim.t),minutes=Math.floor(seconds/60);$('clock').textContent=String(stage().hour+Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');$('progress').style.width=(seconds/E.DURATION*100)+'%';$('mode-label').textContent=state.paused?'一時停止':state.mode==='running'?'20分を計測中':state.mode==='result'?'計測おわり':'設計中 / 試走';$('view-label').textContent=(state.before?'変更前の原案':'あなたの案')+' / '+(state.mode==='running'?'計測':state.mode==='result'?'終了':'試走');}
function showModal(html){previousFocus=document.activeElement;$('modal-body').innerHTML=html;if(!$('modal').open)$('modal').showModal();$$('[data-close]').forEach(b=>b.addEventListener('click',closeModal));}
function closeModal(){$('modal').close();if(previousFocus&&typeof previousFocus.focus==='function')previousFocus.focus();}
function modalFrame(content){return `<div class="modal-content"><button class="modal-close" data-close aria-label="閉じる">×</button>${content}</div>`;}
function help(){showModal(modalFrame(`<div class="eyebrow">HOW TO UNTANGLE A MORNING</div><h2>大きく変えずに、<br>大きく変わる。</h2><p>街の朝を受け持つ、名もない修繕係。<br>許される変更は3つ。予算も、時間も、無限ではありません。</p><div class="help-steps"><div class="help-step"><b>01</b><div><strong>詰まりを見る。</strong><p>止まっている列だけでなく、その少し先を見ます。車体の色は変わりません。停止は動きとブレーキランプで、詰まりの範囲は「詰まりを読む」で確認できます。街はドラッグで回転、ホイールで拡大。スマートフォンは1本指で回転、2本指で拡大と移動。番号を選び、「近くで見る」で交差点へ寄れます。</p></div></div><div class="help-step"><b>02</b><div><strong>時を編む。道を繕う。</strong><p>青信号の配分・タイミング・連動・右折専用信号。あるいは右折レーンや高架。変更を「書き込む」と1手です。同じ設定の修正は手数を増やしません。</p></div></div><div class="help-step"><b>03</b><div><strong>同じ朝で、比べる。</strong><p>「朝を流す」で20分を計測。原案とまったく同じ車・出発時刻で比べます。「結果まで」で計算を最後まで進められます。</p></div></div></div><h3>同じ街を、違う高さで見る。</h3><p>「模型」で街全体。「俯瞰」で接続。「路上」で選択した交差点の高さへ。「追走」で一台の車を追い、その車の待ち時間を見る。視点の変更は無料で、評価には影響しません。3Dの建物・山・川は舞台装置で、道を塞ぐ障害物ではありません。</p><h3>誰かに押しつけた時間は、消えない。</h3><p>総待ち時間を目標以上減らし、歩行者の平均待ちを原案＋6秒以内、脇道を＋15秒以内に。到着台数も、原案から4台相当を超えて減らさないこと。地図に入れず待つ車も計上されます。</p><p>クリアで1つの印。改善率が目標＋8ポイント以上なら、もう1つ。予算60%以内なら、さらに1つ（最大3つ）。変更を取り消したり、何度試したりしてもペナルティはありません。</p><small>図の車1つは2台相当。歩行者1点は2人相当。待ち時間は乗車人数で重み付け。バスは車より多くの人の時間を運びます。すべてゲーム用の簡易モデルで、実務の交通設計には使えません。</small><p><small>操作：番号 1–5 = 交差点 ／ Space = 一時停止 ／ B = 原案と比較 ／ Z = ひとつ戻す。O = 模型 ／ T = 俯瞰 ／ C = 路上 ／ F = 交差点へ。</small></p><button class="primary close-bottom" data-close>朝に戻る <span>→</span></button>`));}
function dataModal(){const rows=E.STAGES.map(s=>{const o=E.observed(s);return `<tr><td>${o.station.name}・${s.hour}時台</td><td>${o.up}</td><td>${o.down}</td><td>${o.up+o.down}</td></tr>`;}).join('');showModal(modalFrame(`<div class="eyebrow">FIELD NOTES / DATA & DESIGN</div><h2>本当の数値から、<br>架空の街をつくる。</h2><p>『朝を、ほどく。』は、公開交通量を種にした交通パズルです。今の松本や、実際の交差点の渋滞を再現した作品ではありません。</p><h3>使っている公開データ</h3><p>国土交通省道路局・長野県「令和3年度 全国道路・街路交通情勢調査 一般交通量調査」。長野県の2024年9月訂正版を参照。原表の小型車・大型車を方向別に合算しています。</p><table class="source-table"><thead><tr><th>観測地点・時刻</th><th>上り</th><th>下り</th><th>台 / 時</th></tr></thead><tbody>${rows}</tbody></table><div class="data-source"><a href="${E.DATA.overview}" target="_blank" rel="noopener noreferrer">長野県・調査結果の公開ページ ↗</a><br><a href="${E.DATA.hourly}#page=9" target="_blank" rel="noopener noreferrer">時間帯別交通量表 9ページ ↗</a><br><a href="${E.DATA.locations}#page=3" target="_blank" rel="noopener noreferrer">箇所別基本表 3ページ ↗</a><br><small>地点 11090：宮田／2021年10月（具体日の記載なし、原表の日付末尾00）<br>地点 11100：鎌田・11110：渚／2021年10月21日<br>原典確認日：2026年9月8日。リアルタイム接続ではありません。</small></div><h3>公開値が、遊びになるまで</h3><p>観測台数に各景の負荷係数（1.03 / 1.20 / 1.04）をかけ、20分相当の流入車を生成。1エージェント＝2台として間引き、同じ乱数シード・同じ発車予定を原案と変更案へ渡します。脇道の交通量は幹線の方向平均に創作した比率をかけています。</p><p>車は前車との間隔、赤信号、曲がり待ち、次の道の空きを見て進みます。信号だけ変えて点数を直接増やす処理はありません。地図の外の車、未到着の車、歩行者も待ち時間に含めます。曲がり待ちと追越しは簡略化しています。</p><h3>実測でないもの</h3><p>地図・地形・交差点名・分岐先・信号設定・飽和交通流率・歩行者数・バス混入率・乗車人数・車速・工事費と効果は創作。バスの割合は大型車データからの推定ではありません。事故リスク、排出量、建設期間、誘発交通、騒音は評価していません。</p><h3>つくりかた</h3><p>路線図が地理から接続関係を取り出すように、街から「待つ・流れる・譲る」を取り出す。詰将棋の手数制限と、版画の少ない色を手がかりに、時間を分け合う小さな遊びにしました。今回は模型の抽象化も加え、屋根、橋脚、車列、影で流れを読める立体の街にしました。絵・動き・音はこの作品のためにコードで制作しています。停止線と車体先端を同じ座標で判定し、進入済みの車は交差点を抜けます。歩行者は歩道で待ち、横断後も歩道を歩きます。右折専用信号と交差点の退出待ちを追加したため、旧版とは採点結果が変わります。現在の2D表示と3D表示は同じモデルです。</p><small>ゲームコード：HODOKU DIORAMA 2.1 / ローカル完結。外部ライブラリ・フォント配布・トラッキングなし。3Dは独自WebGL描画。WebGLを利用できない環境では2D表示へ切り替わります。音は最初はOFF。成績と設計はブラウザ内だけに保存し、保存できない環境でも遊べます。</small><button id="import-plan" class="secondary">共有された案を読み込む <span>↓</span></button><button class="primary close-bottom" data-close>街に戻る <span>→</span></button>`));$('import-plan').addEventListener('click',importModal);}
function chart(before,after){const b=before.series,a=after.series,max=Math.max(1,...b.map(x=>x.q),...a.map(x=>x.q))*1.08;const pathFor=xs=>xs.map((v,i)=>(i?'L':'M')+(v.t/E.DURATION*620).toFixed(1)+','+(85-v.q/max*76).toFixed(1)).join(' ');return `<div class="result-chart"><svg viewBox="0 0 620 96" role="img" aria-label="20分間の待ち行列。破線は原案、実線はあなたの案。"><path d="M0 85H620" stroke="#cbcebe" stroke-width="1"/><path d="${pathFor(b)}" fill="none" stroke="#9fa793" stroke-width="1.8" stroke-dasharray="4 4"/><path d="${pathFor(a)}" fill="none" stroke="#45685b" stroke-width="2.3"/></svg></div><div class="chart-legend"><span>··· 原案の列</span><span>― あなたの案の列</span><span>20 MINUTES</span></div>`;}
function showResults(){const r=state.result;if(!r)return;const b=r.before,a=r.after;let heading=r.win?'朝が、軽くなった。':r.improvement>0?'少し、ほどけた。':'もう一度、街を見る。';let explanation='';if(!state.plan.length)explanation='何も変えていないので、原案と同じ結果です。まず一か所だけ変えて、違いを見てみましょう。';else if(!r.pedOK)explanation='車の流れと引き換えに、歩行者の平均待ちが許容範囲を超えました。主道の青を少し返すか、別の場所を直してみてください。';else if(!r.sideOK)explanation='主道の改善が、脇道へ待ち時間を押し出しています。混んでいる交差点の先と横にも目を向けてみましょう。';else if(!r.completeOK)explanation='到着した車が原案より少なくなりました。地図の入口でせき止めるのではなく、最後まで流せる案にしましょう。';else if(r.win)explanation='街全体の待ち時間を減らし、歩行者と脇道の条件も守れました。さらに少ない工費で、同じ朝をほどけるでしょうか。';else explanation=stage().hint;
 const row=(label,old,now,unit,ok=true)=>`<tr><td>${label}</td><td>${fmt(old,1)}${unit}</td><td>${fmt(now,1)}${unit}</td><td class="${!ok?'bad':now>old?'tolerated':'good'}">${signed(now-old,1)}${unit}</td></tr>`;
 showModal(modalFrame(`<div class="result-top"><div><div class="eyebrow">SCENE ${stage().no} / AFTER THE MORNING</div><h2>${heading}</h2><small>${stage().name}</small></div><div class="stamp"><b>${r.win?'解けた':'再考'}</b><span>${'●'.repeat(r.stars)}${'○'.repeat(3-r.stars)}</span></div></div><div class="result-hero ${r.saved<0?'negative':''}"><div class="saved"><small>${r.saved>=0?'この街に返した時間':'この街で増えた待ち時間'}</small><strong>${fmt(Math.abs(r.saved))}</strong><span>人・分</span></div><div class="improvement">${r.improvement>=0?'−':'＋'}${fmt(Math.abs(r.improvement),1)}%<small>街全体の待ち時間</small></div></div><small>シミュレーション上の時間です。実際の短縮効果ではありません。</small>${chart(b,a)}<table class="result-table"><thead><tr><th>街に残ったもの</th><th>原案</th><th>あなたの案</th><th>差</th></tr></thead><tbody>${row('車・バス利用者の待ち',b.vehicleAvg,a.vehicleAvg,'秒',a.vehicleAvg<=b.vehicleAvg)}${row('歩行者の平均待ち',b.pedAvg,a.pedAvg,'秒',r.pedOK)}${row('脇道から来た人の待ち',b.sideAvg,a.sideAvg,'秒',r.sideOK)}<tr><td>到着した車（換算）</td><td>${b.completed*2}台</td><td>${a.completed*2}台</td><td class="${r.completeOK?'good':'bad'}">${signed((a.completed-b.completed)*2)}台</td></tr><tr><td>未到着・入口待ち（換算）</td><td>${b.unfinished*2}台</td><td>${a.unfinished*2}台</td><td>${signed((a.unfinished-b.unfinished)*2)}台</td></tr></tbody></table><div class="result-assessment">${explanation}</div><div class="result-footer"><span>${state.plan.length} / 3 手</span><span>工費 ${r.cost} / ${stage().budget} pt</span><span>記録 ${r.score} pt</span></div><div class="result-actions"><button id="retry" class="secondary">同じ朝を、もう一度 <span>↶</span></button><button id="next-stage" class="primary">${state.stage<2?'次の景へ':'最初の景へ'} <span>→</span></button></div><button id="share-result" class="result-share">この案を共有する</button>`));$('retry').addEventListener('click',retry);$('next-stage').addEventListener('click',()=>{closeModal();changeStage((state.stage+1)%3);});$('share-result').addEventListener('click',sharePlan);}
function encodePlan(){return btoa(JSON.stringify({v:1,stage:state.stage,plan:state.plan}));}
function decodePlan(code){if(typeof code!=='string'||code.length>8000)throw new Error('invalid');const data=JSON.parse(atob(code.trim().replace(/^HODOKU1:/,'')));if(data.v!==1||!Number.isInteger(data.stage)||data.stage<0||data.stage>2||!E.validatePlan(E.STAGES[data.stage],data.plan).ok)throw new Error('invalid');return data;}
async function sharePlan(){const code='HODOKU1:'+encodePlan(),r=state.result;let str=`朝を、ほどく。第${state.stage+1}景「${stage().name}」\n${state.plan.length}手・予算${r.cost}ptで、待ち時間 ${r.improvement>=0?'−':'＋'}${fmt(Math.abs(r.improvement),1)}%。\n${state.plan.map(planDescription).join('\n')}\n\n${code}`;
 if(/^https?:$/.test(location.protocol))str+='\n'+location.href.split('#')[0]+'#plan='+encodePlan();
 try{if(navigator.share){await navigator.share({title:'朝を、ほどく。',text:str});return;}if(navigator.clipboard){await navigator.clipboard.writeText(str);toast('案のコードをコピーしました。「データと制作」から読み込めます。');return;}}catch(e){if(e.name==='AbortError')return;}
 showModal(modalFrame('<div class="eyebrow">SHARE YOUR THREE STITCHES</div><h2>この朝を、渡す。</h2><p>下のコードをコピーして渡してください。「データと制作」→「案を読み込む」で、同じ変更を再現できます。</p><textarea id="share-code" readonly aria-label="共有する案のコード" style="width:100%;min-height:130px;background:#f8f5ed;color:var(--ink);border:1px solid var(--line);padding:13px;font:11px/1.8 var(--mono)"></textarea><button class="primary close-bottom" data-close>街に戻る <span>→</span></button>'));$('share-code').value=code;$('share-code').select();}
function importModal(){showModal(modalFrame('<div class="eyebrow">A MORNING FROM SOMEONE ELSE</div><h2>誰かの三手を、試す。</h2><p>HODOKU1: から始まる案のコードを貼り付けてください。現在の設計はこの案に置き換わります。</p><textarea id="import-code" aria-label="案のコード" placeholder="HODOKU1:…" style="width:100%;min-height:110px;background:#f8f5ed;color:var(--ink);border:1px solid var(--line);padding:13px;font:11px/1.8 var(--mono)"></textarea><button id="do-import" class="primary close-bottom">この案を読み込む <span>→</span></button>'));$('do-import').addEventListener('click',()=>{try{const v=decodePlan($('import-code').value);closeModal();state.stage=v.stage;state.plan=v.plan;state.selected=1;startGame();persist();toast('案を読み込みました。同じ朝で試せます。');}catch(_){toast('案のコードを読み込めませんでした。先頭から末尾まで確認してください。');}});}
// Sound is opt-in, generated locally, throttled, and never tied to flashing.
const audio={ctx:null,lastNote:0,notes:[146.83,196,220,293.66,329.63],
 async toggle(){try{if(!this.ctx)this.ctx=new (root.AudioContext||root.webkitAudioContext)();await this.ctx.resume();state.sound=!state.sound;$('sound').setAttribute('aria-pressed',String(state.sound));$('sound').innerHTML='音 <span>'+(state.sound?'ON':'OFF')+'</span>';if(state.sound)this.tap(1);}catch(_){toast('このブラウザでは音を開始できません。音なしでも遊べます。');}},
 note(freq,duration=.65,vol=.025){if(!state.sound||!this.ctx||this.ctx.state!=='running')return;const now=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(vol,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(this.ctx.destination);o.start(now);o.stop(now+duration+.05);},
 tap(which){this.note(which<0?110:which===0?293.66:which===1?440:587.33,.2,.017);},
 flow(sim){if(!state.sound||!sim.exitEvents.length||!this.ctx)return;const now=this.ctx.currentTime;if(now-this.lastNote<.42)return;this.lastNote=now;const c=sim.exitEvents[0];this.note(this.notes[c.id%5]*(c.bus?.5:1),.9,.014);},
 chord(win){if(win)[196,293.66,440].forEach((f,i)=>setTimeout(()=>this.note(f,1.8,.03),i*120));else this.note(146.83,1.1,.025);}
};
$('start').addEventListener('click',startGame);$('brand').addEventListener('click',cover);$('help').addEventListener('click',help);$('data').addEventListener('click',dataModal);$('sound').addEventListener('click',()=>audio.toggle());$('run').addEventListener('click',run);$('skip').addEventListener('click',skip);
$('clear-plan').addEventListener('click',()=>{if(state.mode==='running')return;state.plan=[];persist();resetSim();updateAll();toast('設計を白紙に戻しました。');});
$('before').addEventListener('click',()=>{state.before=!state.before;updateAll();});$('heat').addEventListener('click',()=>{state.heat=!state.heat;updateAll();});
$('pause').addEventListener('click',()=>{if(state.mode==='result'){showResults();return;}state.paused=!state.paused;last=0;updateAll();});$('speed').addEventListener('click',()=>{state.speed=state.speed===20?60:state.speed===60?180:20;updateAll();});
$$('[data-tool-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.toolTab;state.ghost=-1;updatePanel();}));
$('map').addEventListener('pointermove',ev=>{state.hover=atlas.hit(ev.clientX,ev.clientY);$('map').style.cursor=state.hover>=0&&state.mode!=='intro'?'pointer':'grab';});$('map').addEventListener('pointerleave',()=>state.hover=-1);$('map').addEventListener('click',ev=>{if(state.mode==='intro')return;const j=atlas.hit(ev.clientX,ev.clientY);if(j>=0)selectNode(j,ev.pointerType==='touch');});
$('modal').addEventListener('click',ev=>{if(ev.target===$('modal')){const r=$('modal').getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)closeModal();}});
$('mobile-run').addEventListener('click',()=>$('run').click());
$('modal').addEventListener('close',()=>{if(state.mode==='result'){state.mode='planning';state.paused=false;resetSim();updateAll();}});
root.addEventListener('keydown',ev=>{if($('modal').open||['INPUT','TEXTAREA','SELECT','BUTTON'].includes(document.activeElement.tagName))return;if(state.mode==='intro')return;if(ev.code==='Space'){ev.preventDefault();$('pause').click();}else if(/^[1-5]$/.test(ev.key))selectNode(Number(ev.key)-1);else if(ev.key.toLowerCase()==='b')$('before').click();else if(ev.key.toLowerCase()==='z'&&!ev.ctrlKey&&!ev.metaKey&&state.plan.length)remove(state.plan.length-1);});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>atlas.setView(b.dataset.view,state.selected)));
$('focus-node').addEventListener('click',()=>{atlas.setView('focus',state.selected);if(innerWidth<761)$('shell').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});
$('zoom-in').addEventListener('click',()=>atlas.zoom(.80));$('zoom-out').addEventListener('click',()=>atlas.zoom(1.25));$('view-home').addEventListener('click',()=>atlas.setView('model',state.selected));
root.addEventListener('hodoku-select',ev=>{if(state.mode==='intro')return;selectNode(ev.detail.node,!!ev.detail.scroll);if(ev.detail.focus)atlas.setView('focus',ev.detail.node);});
root.addEventListener('keydown',ev=>{if($('modal').open||state.mode==='intro'||['INPUT','TEXTAREA','SELECT','BUTTON'].includes(document.activeElement.tagName)||ev.ctrlKey||ev.metaKey)return;const views={o:'model',t:'top',c:'street',f:'focus'};if(views[ev.key.toLowerCase()]){ev.preventDefault();atlas.setView(views[ev.key.toLowerCase()],state.selected);}});
root.addEventListener('resize',()=>atlas.resize());new ResizeObserver(()=>atlas.resize()).observe($('map'));
function frame(now){const delta=last?Math.min(.1,(now-last)/1000):0;last=now;if(!document.hidden&&!state.paused&&!$('modal').open&&!computing){const speed=state.mode==='intro'?5:state.mode==='running'?state.speed:Math.min(12,state.speed);acc+=delta*speed;let steps=0;while(acc>=E.DT&&steps<90){beforeSim.step();afterSim.step();audio.flow(afterSim);acc-=E.DT;steps++;if(afterSim.t>=E.DURATION){if(state.mode==='running'){completeRun();break;}else if(state.mode!=='result'){resetSim();break;}}}}
 atlas.render(shownSim(),{selected:state.selected,heat:state.heat,hover:state.hover,intro:state.mode==='intro',ghostFlyover:state.ghost,alpha:state.paused?1:acc/E.DT});if(now-lastUI>220){updateLive();lastUI=now;}requestAnimationFrame(frame);
}
resetSim();updateAll();
try{const hash=location.hash;if(hash.startsWith('#plan=')){const v=decodePlan(hash.slice(6));state.stage=v.stage;state.plan=v.plan;startGame();persist();}}catch(_){toast('共有リンクの案を読み込めませんでした。');}
root.HODOKU_APP={getState:()=>({stage:state.stage,mode:state.mode,plan:JSON.parse(JSON.stringify(state.plan)),selected:state.selected,before:state.before,paused:state.paused,budget:stage().budget-(E.validatePlan(stage(),state.plan).cost||0),time:afterSim.t,result:state.result,conservation:afterSim.conservation()}),engine:E,view:()=>atlas.info()};
requestAnimationFrame(frame);
})(globalThis);
